"""Seed data aligned with the frontend contracts."""

from __future__ import annotations

from copy import deepcopy

INTERNAL_EMAIL_DOMAIN = "@gm.uit.edu.vn"
ROLE_ROUTE_MATRIX = {
    "guest": {
        "allowed_shells": ["public", "auth", "system"],
        "allowed_routes": ["/", "/chat", "/documents/:id", "/auth/login", "/auth/callback", "/403"],
        "requires_internal_email": False,
    },
    "student": {
        "allowed_shells": ["public", "auth", "system"],
        "allowed_routes": ["/", "/chat", "/documents/:id", "/auth/login", "/auth/callback", "/403"],
        "requires_internal_email": False,
    },
    "lecturer": {
        "allowed_shells": ["public", "auth", "portal", "system"],
        "allowed_routes": [
            "/",
            "/chat",
            "/documents/:id",
            "/auth/login",
            "/auth/callback",
            "/403",
            "/portal",
            "/portal/upload",
            "/portal/submissions",
            "/portal/submissions/:id",
        ],
        "requires_internal_email": True,
    },
    "operator": {
        "allowed_shells": ["public", "auth", "portal", "system"],
        "allowed_routes": [
            "/",
            "/chat",
            "/documents/:id",
            "/auth/login",
            "/auth/callback",
            "/403",
            "/portal",
            "/portal/upload",
            "/portal/submissions",
            "/portal/submissions/:id",
            "/portal/review",
            "/portal/library",
            "/portal/jobs",
        ],
        "requires_internal_email": True,
    },
    "admin": {
        "allowed_shells": ["public", "auth", "portal", "admin", "system"],
        "allowed_routes": [
            "/",
            "/chat",
            "/documents/:id",
            "/auth/login",
            "/auth/callback",
            "/403",
            "/portal",
            "/portal/upload",
            "/portal/submissions",
            "/portal/submissions/:id",
            "/portal/review",
            "/portal/library",
            "/portal/jobs",
            "/admin/users",
            "/admin/roles",
            "/admin/settings",
            "/admin/audit-logs",
        ],
        "requires_internal_email": True,
    },
}

SESSION_FIXTURES = {
    "guest": {
        "session_id": "session-guest",
        "status": "anonymous",
        "user": {
            "id": "guest",
            "name": "Guest User",
            "email": "guest@public.uit.edu.vn",
            "role": "guest",
            "department": "Public",
            "avatar_initials": "GU",
        },
    },
    "student": {
        "session_id": "session-student",
        "status": "authenticated",
        "user": {
            "id": "user-student",
            "name": "Nguyen Thi Student",
            "email": "student@uit.edu.vn",
            "role": "student",
            "department": "Student",
            "avatar_initials": "NS",
        },
    },
    "lecturer": {
        "session_id": "session-lecturer",
        "status": "authenticated",
        "user": {
            "id": "user-lecturer",
            "name": "Pham Van Lecturer",
            "email": "lecturer@gm.uit.edu.vn",
            "role": "lecturer",
            "department": "Faculty of Computer Science",
            "avatar_initials": "PL",
        },
    },
    "operator": {
        "session_id": "session-operator",
        "status": "authenticated",
        "user": {
            "id": "user-operator",
            "name": "Le Thi Operator",
            "email": "operator@gm.uit.edu.vn",
            "role": "operator",
            "department": "Knowledge Operations",
            "avatar_initials": "LO",
        },
    },
    "admin": {
        "session_id": "session-admin",
        "status": "authenticated",
        "user": {
            "id": "user-admin",
            "name": "Tran Van Admin",
            "email": "admin@gm.uit.edu.vn",
            "role": "admin",
            "department": "System Administration",
            "avatar_initials": "TA",
        },
    },
}

DOCUMENT_FIXTURES = [
    {
        "id": "doc-001",
        "title": "Quy dinh hoc vu 2024-2025",
        "owner_name": "Pham Van Lecturer",
        "owner_email": "lecturer@gm.uit.edu.vn",
        "lifecycle_status": "approved",
        "processing_status": "completed",
        "created_at": "2026-03-15T08:00:00.000Z",
        "updated_at": "2026-03-16T08:30:00.000Z",
        "temporal_metadata": {
            "document_type": "regulation",
            "extraction_method": "llm",
            "temporal_confidence": 0.93,
            "temporal_reasoning": "Detected valid range and academic year from section 1 and 2.",
            "valid_from": "2024-09-01",
            "valid_until": "2025-08-31",
            "academic_year": "2024-2025",
            "cohort_years": ["2022", "2023", "2024"],
            "document_number": "123/QD-UIT",
            "amends_documents": [],
        },
        "system_metadata": {
            "file_source": "/uploads/quy-dinh-hoc-vu-2024-2025.pdf",
            "indexed_at": "2026-03-16T08:31:00.000Z",
            "content_hash": "4c3a430ec55b4f7509b8d7fc1b03017aa0f84ca4a690d8f0f0c26ee23c0f4aab",
            "is_archived": False,
            "version_number": 2,
        },
        "supplemental_metadata": {
            "title": "Quy dinh hoc vu 2024-2025",
            "issuing_unit": "Phong Dao tao Dai hoc",
            "tags": ["hoc-vu", "quy-che"],
            "visibility_scope": "public",
            "notes": "Displayed in public assistant results.",
        },
        "traceability": {
            "source_submission_id": None,
            "source_review_id": None,
            "reviewed_by_name": "Le Thi Operator",
            "published_at": "2026-03-16T08:31:00.000Z",
            "publication_reason": "Approved revision with clarified cohort range and indexing provenance.",
        },
        "version_history": [
            {
                "id": "doc-001-v2",
                "version_number": 2,
                "created_at": "2026-03-16T08:31:00.000Z",
                "created_by_name": "Le Thi Operator",
                "change_summary": "Approved revision with clarified cohort range and updated indexing provenance.",
                "file_source": "/uploads/quy-dinh-hoc-vu-2024-2025.pdf",
                "content_hash": "4c3a430ec55b4f7509b8d7fc1b03017aa0f84ca4a690d8f0f0c26ee23c0f4aab",
                "is_current": True,
                "source_submission_id": None,
                "source_review_id": None,
                "change_highlights": [
                    "Clarified cohort coverage for 2024 intake.",
                    "Updated indexed provenance after operator review.",
                ],
            },
            {
                "id": "doc-001-v1",
                "version_number": 1,
                "created_at": "2026-03-15T08:05:00.000Z",
                "created_by_name": "Pham Van Lecturer",
                "change_summary": "Initial upload snapshot before operator confirmation.",
                "file_source": "/uploads/quy-dinh-hoc-vu-2024-2025-v1.pdf",
                "content_hash": "29d9b0f5b6fd38df9065f6ee4b4f15d9d4da045e7c1a5327f1ea9f7eafe83382",
                "is_current": False,
                "source_submission_id": None,
                "source_review_id": None,
                "change_highlights": ["Initial lecturer snapshot before operator confirmation."],
            },
        ],
        "activity_history": [],
    },
    {
        "id": "doc-002",
        "title": "Thong bao hoc phi hoc ky 2",
        "owner_name": "Le Thi Operator",
        "owner_email": "operator@gm.uit.edu.vn",
        "lifecycle_status": "pending_review",
        "processing_status": "extracting",
        "created_at": "2026-03-18T04:12:00.000Z",
        "updated_at": "2026-03-18T04:15:00.000Z",
        "temporal_metadata": {
            "document_type": "fee_notice",
            "extraction_method": "regex",
            "temporal_confidence": 0.65,
            "temporal_reasoning": "Found fee semester pattern but no explicit valid_until date.",
            "valid_from": "2026-02-01",
            "valid_until": None,
            "academic_year": "2025-2026",
            "cohort_years": ["2024", "2025"],
            "document_number": None,
            "amends_documents": [],
        },
        "system_metadata": {
            "file_source": "/uploads/thong-bao-hoc-phi-hk2.docx",
            "indexed_at": "2026-03-18T04:16:00.000Z",
            "content_hash": "f73cbe50f57b31cb5db54432f11ce1af2b3f915d7f7068cd1942e84551fdd201",
            "is_archived": False,
            "version_number": 1,
        },
        "supplemental_metadata": {
            "title": "Thong bao hoc phi hoc ky 2",
            "issuing_unit": "Phong Ke hoach - Tai chinh",
            "tags": ["hoc-phi"],
            "visibility_scope": "internal",
            "notes": "Pending operator review before publish.",
        },
        "traceability": {
            "source_submission_id": None,
            "source_review_id": None,
            "reviewed_by_name": None,
            "published_at": None,
            "publication_reason": None,
        },
        "version_history": [
            {
                "id": "doc-002-v1",
                "version_number": 1,
                "created_at": "2026-03-18T04:16:00.000Z",
                "created_by_name": "Le Thi Operator",
                "change_summary": "Initial extraction snapshot created from uploaded DOCX notice.",
                "file_source": "/uploads/thong-bao-hoc-phi-hk2.docx",
                "content_hash": "f73cbe50f57b31cb5db54432f11ce1af2b3f915d7f7068cd1942e84551fdd201",
                "is_current": True,
                "source_submission_id": None,
                "source_review_id": None,
                "change_highlights": ["Initial extraction snapshot retained for internal review only."],
            },
        ],
        "activity_history": [
            {
                "id": "audit-004b",
                "actor_name": "Le Thi Operator",
                "actor_role": "operator",
                "action": "reindex_document",
                "target_type": "document",
                "target_id": "doc-002",
                "target_label": "Thong bao hoc phi hoc ky 2",
                "created_at": "2026-03-18T04:17:00.000Z",
            },
        ],
    },
    {
        "id": "doc-003",
        "title": "Thong bao hoc bong doanh nghiep",
        "owner_name": "Tran Van Admin",
        "owner_email": "admin@gm.uit.edu.vn",
        "lifecycle_status": "archived",
        "processing_status": "completed",
        "created_at": "2025-12-10T03:00:00.000Z",
        "updated_at": "2026-02-01T09:20:00.000Z",
        "temporal_metadata": {
            "document_type": "scholarship",
            "extraction_method": "filename_fallback",
            "temporal_confidence": 0.4,
            "temporal_reasoning": "No date found. Document kept as archived reference only.",
            "valid_from": None,
            "valid_until": None,
            "academic_year": None,
            "cohort_years": [],
            "document_number": None,
            "amends_documents": ["HB-2024-12"],
        },
        "system_metadata": {
            "file_source": "/uploads/hoc-bong-doanh-nghiep.pdf",
            "indexed_at": "2025-12-10T03:02:00.000Z",
            "content_hash": "328e12c4cab9798b35fc4fd61ad1da4f3ffdb19b796d328bcb630374ac14f5ab",
            "is_archived": True,
            "version_number": 1,
        },
        "supplemental_metadata": {
            "title": "Thong bao hoc bong doanh nghiep",
            "issuing_unit": "Phong Cong tac Sinh vien",
            "tags": ["hoc-bong"],
            "visibility_scope": "public",
            "notes": "Archived after new scholarship bulletin superseded it.",
        },
        "traceability": {
            "source_submission_id": None,
            "source_review_id": None,
            "reviewed_by_name": "Tran Van Admin",
            "published_at": "2025-12-10T03:02:00.000Z",
            "publication_reason": "Preserved as historical reference and later archived.",
        },
        "version_history": [
            {
                "id": "doc-003-v1",
                "version_number": 1,
                "created_at": "2025-12-10T03:02:00.000Z",
                "created_by_name": "Tran Van Admin",
                "change_summary": "Original scholarship notice preserved as historical reference.",
                "file_source": "/uploads/hoc-bong-doanh-nghiep.pdf",
                "content_hash": "328e12c4cab9798b35fc4fd61ad1da4f3ffdb19b796d328bcb630374ac14f5ab",
                "is_current": True,
                "source_submission_id": None,
                "source_review_id": None,
                "change_highlights": ["Archived notice kept for historical scholarship lookups."],
            },
        ],
        "activity_history": [
            {
                "id": "audit-004",
                "actor_name": "Tran Van Admin",
                "actor_role": "admin",
                "action": "archive_document",
                "target_type": "document",
                "target_id": "doc-003",
                "target_label": "Thong bao hoc bong doanh nghiep",
                "created_at": "2026-02-01T09:20:00.000Z",
            },
        ],
    },
    {
        "id": "doc-004",
        "title": "Thong bao lich dang ky mon hoc",
        "owner_name": "Le Thi Operator",
        "owner_email": "operator@gm.uit.edu.vn",
        "lifecycle_status": "approved",
        "processing_status": "completed",
        "created_at": "2026-03-17T05:05:00.000Z",
        "updated_at": "2026-03-17T05:40:00.000Z",
        "temporal_metadata": {
            "document_type": "announcement",
            "extraction_method": "regex",
            "temporal_confidence": 0.9,
            "temporal_reasoning": "Reviewed publication dates and enrollment timeline from the official source page.",
            "valid_from": "2026-03-20",
            "valid_until": "2026-04-05",
            "academic_year": "2025-2026",
            "cohort_years": ["2024", "2025", "2026"],
            "document_number": "88/TB-UIT",
            "amends_documents": [],
        },
        "system_metadata": {
            "file_source": "https://uit.edu.vn/dang-ky-mon-hoc",
            "indexed_at": "2026-03-17T05:33:00.000Z",
            "content_hash": "8c63c494a993d9347615387da779ce3c6b74ff78c08f9f941d190ced6a008fe1",
            "is_archived": False,
            "version_number": 1,
        },
        "supplemental_metadata": {
            "title": "Thong bao lich dang ky mon hoc",
            "issuing_unit": "Phong Dao tao Dai hoc",
            "tags": ["dang-ky-mon-hoc", "thong-bao"],
            "visibility_scope": "public",
            "notes": "Approved from submission sub-002 and now eligible for student-facing assistant answers.",
        },
        "traceability": {
            "source_submission_id": "sub-002",
            "source_review_id": "review-002",
            "reviewed_by_name": "Le Thi Operator",
            "published_at": "2026-03-17T05:33:00.000Z",
            "publication_reason": "Approved for public student-facing chat after date range verification.",
        },
        "version_history": [
            {
                "id": "doc-004-v1",
                "version_number": 1,
                "created_at": "2026-03-17T05:33:00.000Z",
                "created_by_name": "Le Thi Operator",
                "change_summary": "Published after review approval from submission sub-002.",
                "file_source": "https://uit.edu.vn/dang-ky-mon-hoc",
                "content_hash": "8c63c494a993d9347615387da779ce3c6b74ff78c08f9f941d190ced6a008fe1",
                "is_current": True,
                "source_submission_id": "sub-002",
                "source_review_id": "review-002",
                "change_highlights": [
                    "Expanded cohort coverage to include 2026.",
                    "Confirmed publishable validity window through 2026-04-05.",
                ],
            },
        ],
        "activity_history": [
            {
                "id": "audit-001",
                "actor_name": "Pham Van Lecturer",
                "actor_role": "lecturer",
                "action": "upload_submission",
                "target_type": "submission",
                "target_id": "sub-002",
                "target_label": "Thong bao lich dang ky mon hoc",
                "created_at": "2026-03-17T05:05:00.000Z",
            },
            {
                "id": "audit-002",
                "actor_name": "Le Thi Operator",
                "actor_role": "operator",
                "action": "approve_review",
                "target_type": "review",
                "target_id": "review-002",
                "target_label": "Thong bao lich dang ky mon hoc",
                "created_at": "2026-03-17T05:31:00.000Z",
            },
            {
                "id": "audit-003",
                "actor_name": "Le Thi Operator",
                "actor_role": "operator",
                "action": "approve_review",
                "target_type": "document",
                "target_id": "doc-004",
                "target_label": "Thong bao lich dang ky mon hoc",
                "created_at": "2026-03-17T05:33:00.000Z",
            },
        ],
    },
]

SUBMISSION_FIXTURES = [
    {
        "id": "sub-001",
        "title": "Quy trinh xin tam hoan hoc phi",
        "source_type": "file",
        "lifecycle_status": "pending_review",
        "processing_status": "indexing",
        "created_at": "2026-03-19T01:15:00.000Z",
        "updated_at": "2026-03-19T01:22:00.000Z",
        "linked_document_id": None,
        "temporal_metadata": {
            "document_type": "procedure",
            "extraction_method": "llm",
            "temporal_confidence": 0.81,
            "temporal_reasoning": "Procedure title and section headers confirm document type.",
            "valid_from": "2026-03-01",
            "valid_until": None,
            "academic_year": None,
            "cohort_years": ["2022", "2023", "2024", "2025"],
            "document_number": "15/TB-UIT",
            "amends_documents": [],
        },
        "system_metadata": {
            "file_source": "/uploads/tam-hoan-hoc-phi.pdf",
            "indexed_at": "2026-03-19T01:23:00.000Z",
            "content_hash": "dfa6f9929ce630f6f2dfe69287a5f44cab7efb3f7276513c4d641b12311cb5ce",
            "is_archived": False,
            "version_number": 1,
        },
        "supplemental_metadata": {
            "title": "Quy trinh xin tam hoan hoc phi",
            "issuing_unit": "Phong Dao tao Dai hoc",
            "tags": ["hoc-phi", "thu-tuc"],
            "visibility_scope": "internal",
            "notes": "Uploaded by lecturer pending review.",
        },
        "traceability": {
            "review_task_id": "review-001",
            "published_document_id": None,
            "reviewed_by_name": "Le Thi Operator",
            "published_at": None,
            "publication_reason": "Waiting for cohort confirmation before publication.",
        },
    },
    {
        "id": "sub-002",
        "title": "Thong bao lich dang ky mon hoc",
        "source_type": "url",
        "lifecycle_status": "approved",
        "processing_status": "completed",
        "created_at": "2026-03-17T05:05:00.000Z",
        "updated_at": "2026-03-17T05:32:00.000Z",
        "linked_document_id": "doc-004",
        "temporal_metadata": {
            "document_type": "announcement",
            "extraction_method": "regex",
            "temporal_confidence": 0.88,
            "temporal_reasoning": "Date ranges extracted from heading and bulletin footer.",
            "valid_from": "2026-03-20",
            "valid_until": "2026-04-05",
            "academic_year": "2025-2026",
            "cohort_years": ["2024", "2025"],
            "document_number": "88/TB-UIT",
            "amends_documents": [],
        },
        "system_metadata": {
            "file_source": "https://uit.edu.vn/dang-ky-mon-hoc",
            "indexed_at": "2026-03-17T05:33:00.000Z",
            "content_hash": "e8de316dbbb9ed2f2ec665cc9070b6ff861adf4a27574f5f46320fe0bbaf9998",
            "is_archived": False,
            "version_number": 1,
        },
        "supplemental_metadata": {
            "title": "Thong bao lich dang ky mon hoc",
            "issuing_unit": "Phong Dao tao Dai hoc",
            "tags": ["dang-ky-mon-hoc"],
            "visibility_scope": "public",
            "notes": "Published to student-facing chat.",
        },
        "traceability": {
            "review_task_id": "review-002",
            "published_document_id": "doc-004",
            "reviewed_by_name": "Le Thi Operator",
            "published_at": "2026-03-17T05:33:00.000Z",
            "publication_reason": "Approved for public student-facing chat after date range verification.",
        },
    },
]

REVIEW_FIXTURES = [
    {
        "id": "review-001",
        "submission_id": "sub-001",
        "published_document_id": None,
        "title": "Quy trinh xin tam hoan hoc phi",
        "source_type": "file",
        "visibility_scope": "internal",
        "submitted_by_name": "Pham Van Lecturer",
        "submitted_by_email": "lecturer@gm.uit.edu.vn",
        "reviewer_name": "Le Thi Operator",
        "status": "pending_review",
        "confidence": 0.81,
        "created_at": "2026-03-19T02:10:00.000Z",
        "extracted_temporal_metadata": deepcopy(SUBMISSION_FIXTURES[0]["temporal_metadata"]),
        "edited_temporal_metadata": {
            **deepcopy(SUBMISSION_FIXTURES[0]["temporal_metadata"]),
            "cohort_years": ["2023", "2024", "2025"],
        },
        "reason": "Need confirmation on cohort range before publish.",
    },
    {
        "id": "review-002",
        "submission_id": "sub-002",
        "published_document_id": "doc-004",
        "title": "Thong bao lich dang ky mon hoc",
        "source_type": "url",
        "visibility_scope": "public",
        "submitted_by_name": "Pham Van Lecturer",
        "submitted_by_email": "lecturer@gm.uit.edu.vn",
        "reviewer_name": "Le Thi Operator",
        "status": "approved",
        "confidence": 0.88,
        "created_at": "2026-03-17T05:20:00.000Z",
        "extracted_temporal_metadata": deepcopy(SUBMISSION_FIXTURES[1]["temporal_metadata"]),
        "edited_temporal_metadata": {
            **deepcopy(SUBMISSION_FIXTURES[1]["temporal_metadata"]),
            "cohort_years": ["2024", "2025", "2026"],
        },
        "reason": "Approved for public student-facing chat after date range verification.",
    },
    {
        "id": "review-003",
        "submission_id": "sub-001",
        "published_document_id": None,
        "title": "Thong bao hoc phi hoc ky 2",
        "source_type": "file",
        "visibility_scope": "internal",
        "submitted_by_name": "Pham Van Lecturer",
        "submitted_by_email": "lecturer@gm.uit.edu.vn",
        "reviewer_name": "Le Thi Operator",
        "status": "rejected",
        "confidence": 0.42,
        "created_at": "2026-03-18T09:10:00.000Z",
        "extracted_temporal_metadata": {
            "document_type": "fee_notice",
            "extraction_method": "filename_fallback",
            "temporal_confidence": 0.42,
            "temporal_reasoning": "Only filename and scattered semester keywords were detected.",
            "valid_from": None,
            "valid_until": None,
            "academic_year": None,
            "cohort_years": [],
            "document_number": None,
            "amends_documents": [],
        },
        "edited_temporal_metadata": {
            "document_type": "fee_notice",
            "extraction_method": "filename_fallback",
            "temporal_confidence": 0.42,
            "temporal_reasoning": "Only filename and scattered semester keywords were detected.",
            "valid_from": None,
            "valid_until": None,
            "academic_year": None,
            "cohort_years": [],
            "document_number": None,
            "amends_documents": [],
        },
        "reason": "Rejected because the uploaded source does not include an official bulletin body or issue number.",
    },
]

JOB_FIXTURES = [
    {
        "id": "job-001",
        "type": "upload",
        "status": "completed",
        "progress": 100,
        "related_title": "Quy dinh hoc vu 2024-2025",
        "started_at": "2026-03-16T08:28:00.000Z",
        "updated_at": "2026-03-16T08:31:00.000Z",
        "message": "Upload completed successfully.",
    },
    {
        "id": "job-002",
        "type": "indexing",
        "status": "failed",
        "progress": 62,
        "related_title": "Quy trinh xin tam hoan hoc phi",
        "started_at": "2026-03-19T01:20:00.000Z",
        "updated_at": "2026-03-19T01:23:00.000Z",
        "message": "Embedding step failed. Retry available.",
    },
    {
        "id": "job-003",
        "type": "scan",
        "status": "indexing",
        "progress": 48,
        "related_title": "UIT public bulletin crawl",
        "started_at": "2026-03-20T02:00:00.000Z",
        "updated_at": "2026-03-20T02:12:00.000Z",
        "message": "Scanning source pages and scheduling updates.",
    },
]

ADMIN_USER_FIXTURES = [
    {
        "id": "usr-001",
        "name": "Nguyen Minh Student",
        "email": "student@uit.edu.vn",
        "role": "student",
        "status": "active",
        "scope": "student_portal",
        "last_active_at": "2026-03-20T07:10:00.000Z",
        "is_internal_domain_compliant": True,
    },
    {
        "id": "usr-002",
        "name": "Pham Van Lecturer",
        "email": "lecturer@gm.uit.edu.vn",
        "role": "lecturer",
        "status": "active",
        "scope": "contributor_portal",
        "last_active_at": "2026-03-20T06:42:00.000Z",
        "is_internal_domain_compliant": True,
    },
    {
        "id": "usr-003",
        "name": "Le Thi Operator",
        "email": "operator@gm.uit.edu.vn",
        "role": "operator",
        "status": "active",
        "scope": "operator_portal",
        "last_active_at": "2026-03-20T06:58:00.000Z",
        "is_internal_domain_compliant": True,
    },
    {
        "id": "usr-004",
        "name": "Tran Van Admin",
        "email": "admin@gm.uit.edu.vn",
        "role": "admin",
        "status": "active",
        "scope": "admin_console",
        "last_active_at": "2026-03-20T05:55:00.000Z",
        "is_internal_domain_compliant": True,
    },
    {
        "id": "usr-005",
        "name": "Invite Pending Lecturer",
        "email": "pending-lecturer@gm.uit.edu.vn",
        "role": "lecturer",
        "status": "invited",
        "scope": "contributor_portal",
        "last_active_at": "2026-03-18T02:10:00.000Z",
        "is_internal_domain_compliant": True,
    },
]

SYSTEM_SETTING_FIXTURES = [
    {
        "group": "auth",
        "key": "sso_provider",
        "label": "Lecturer SSO provider",
        "value": "UIT Google Workspace SSO",
        "description": "Internal staff accounts must authenticate via institutional SSO.",
        "is_sensitive": False,
        "source": "mock_policy",
    },
    {
        "group": "auth",
        "key": "internal_domain_rule",
        "label": "Internal domain rule",
        "value": "@gm.uit.edu.vn required for lecturer/operator/admin",
        "description": "Contributor and admin roles are valid only with the institutional mail domain.",
        "is_sensitive": False,
        "source": "derived_contract",
    },
    {
        "group": "ingestion",
        "key": "publication_gate",
        "label": "Publication gate",
        "value": "Review approval required before public release",
        "description": "Lecturer uploads remain provisional until the operator review step approves them.",
        "is_sensitive": False,
        "source": "derived_contract",
    },
    {
        "group": "publication",
        "key": "admin_break_glass_override",
        "label": "Admin break-glass override",
        "value": "Admin may execute operator-owned remediation actions with explicit audit trail",
        "description": "Archive, reindex, retry and review decisions remain operator-owned by default; admin uses them only for audited support incidents.",
        "is_sensitive": False,
        "source": "derived_contract",
    },
    {
        "group": "publication",
        "key": "system_api_key",
        "label": "Backend ingestion secret",
        "value": "stored-in-secret-manager",
        "description": "Credentials are managed server-side and never shown in frontend cleartext.",
        "is_sensitive": True,
        "source": "mock_policy",
    },
    {
        "group": "chat",
        "key": "citation_policy",
        "label": "Citation policy",
        "value": "Student-facing answers must display references and warnings",
        "description": "Low-confidence, pending-review or archived sources require explicit UI warnings.",
        "is_sensitive": False,
        "source": "derived_contract",
    },
]

AUDIT_LOG_FIXTURES = [
    {
        "id": "audit-001",
        "actor_name": "Pham Van Lecturer",
        "actor_role": "lecturer",
        "action": "upload_submission",
        "target_type": "submission",
        "target_id": "sub-002",
        "target_label": "Thong bao lich dang ky mon hoc",
        "created_at": "2026-03-17T05:05:00.000Z",
    },
    {
        "id": "audit-002",
        "actor_name": "Le Thi Operator",
        "actor_role": "operator",
        "action": "approve_review",
        "target_type": "review",
        "target_id": "review-002",
        "target_label": "Thong bao lich dang ky mon hoc",
        "created_at": "2026-03-17T05:31:00.000Z",
    },
    {
        "id": "audit-003",
        "actor_name": "Le Thi Operator",
        "actor_role": "operator",
        "action": "approve_review",
        "target_type": "document",
        "target_id": "doc-004",
        "target_label": "Thong bao lich dang ky mon hoc",
        "created_at": "2026-03-17T05:33:00.000Z",
    },
    {
        "id": "audit-004",
        "actor_name": "Tran Van Admin",
        "actor_role": "admin",
        "action": "archive_document",
        "target_type": "document",
        "target_id": "doc-003",
        "target_label": "Thong bao hoc bong doanh nghiep",
        "created_at": "2026-02-01T09:20:00.000Z",
    },
    {
        "id": "audit-004b",
        "actor_name": "Le Thi Operator",
        "actor_role": "operator",
        "action": "reindex_document",
        "target_type": "document",
        "target_id": "doc-002",
        "target_label": "Thong bao hoc phi hoc ky 2",
        "created_at": "2026-03-18T04:17:00.000Z",
    },
    {
        "id": "audit-005",
        "actor_name": "Tran Van Admin",
        "actor_role": "admin",
        "action": "role_switch",
        "target_type": "session",
        "target_id": "session-admin",
        "target_label": "Demo role switch to admin",
        "created_at": "2026-03-20T07:30:00.000Z",
    },
]

DENSE_AUDIT_LOG_FIXTURES = [
    {
        "id": "audit-000",
        "actor_name": "Nguyen Minh Student",
        "actor_role": "student",
        "action": "login",
        "target_type": "session",
        "target_id": "session-student",
        "target_label": "Student portal session",
        "created_at": "2026-03-20T06:15:00.000Z",
    },
    *deepcopy(AUDIT_LOG_FIXTURES),
    {
        "id": "audit-006",
        "actor_name": "Le Thi Operator",
        "actor_role": "operator",
        "action": "reject_review",
        "target_type": "review",
        "target_id": "review-003",
        "target_label": "Thong bao hoc phi hoc ky 2",
        "created_at": "2026-03-18T16:15:00.000Z",
    },
]

CONVERSATION_FIXTURES = [
    {
        "id": "conv-001",
        "title": "Tra cuu hoc phi",
        "updated_at": "2026-03-20T03:00:05.000Z",
        "messages": [
            {
                "id": "msg-001",
                "role": "user",
                "content": "Hoc phi hoc ky 2 nam nay bao nhieu?",
                "created_at": "2026-03-20T03:00:00.000Z",
                "references": [],
                "warnings": [],
            },
            {
                "id": "msg-002",
                "role": "assistant",
                "content": "Hoc phi hien tai dang duoc tham chieu tu thong bao hoc phi hoc ky 2. Ban nen kiem tra lai theo khoa va so tin chi truoc khi nop.",
                "created_at": "2026-03-20T03:00:05.000Z",
                "confidence": 0.72,
                "references": [
                    {
                        "id": "ref-001",
                        "title": "Thong bao hoc phi hoc ky 2",
                        "href": "/documents/doc-002",
                        "excerpt": "Thong bao muc hoc phi theo so tin chi va thoi han thanh toan.",
                        "status_label": "Pending review",
                    }
                ],
                "warnings": [{"code": "low_confidence", "message": "Tai lieu nguon dang o trang thai pending review."}],
            },
        ],
    },
    {
        "id": "conv-002",
        "title": "Dieu kien hoc bong",
        "updated_at": "2026-03-19T06:15:00.000Z",
        "messages": [
            {
                "id": "msg-003",
                "role": "user",
                "content": "Dieu kien hoc bong doanh nghiep la gi?",
                "created_at": "2026-03-19T06:14:00.000Z",
                "references": [],
                "warnings": [],
            },
            {
                "id": "msg-004",
                "role": "assistant",
                "content": "Thong tin hoc bong cu da duoc luu tru. Ban nen lien he phong CTSV de nhan ban cap nhat moi nhat.",
                "created_at": "2026-03-19T06:15:00.000Z",
                "confidence": 0.41,
                "references": [
                    {
                        "id": "ref-002",
                        "title": "Thong bao hoc bong doanh nghiep",
                        "href": "/documents/doc-003",
                        "excerpt": "Thong bao cu da het hieu luc.",
                        "status_label": "Archived",
                    }
                ],
                "warnings": [{"code": "archived_source", "message": "Nguon tham chieu da duoc archive."}],
            },
        ],
    },
    {
        "id": "conv-003",
        "title": "Lich dang ky mon hoc",
        "updated_at": "2026-03-20T07:30:00.000Z",
        "messages": [
            {
                "id": "msg-005",
                "role": "user",
                "content": "Lich dang ky mon hoc cho khoa 2024 bat dau khi nao?",
                "created_at": "2026-03-20T07:29:00.000Z",
                "references": [],
                "warnings": [],
            },
            {
                "id": "msg-006",
                "role": "assistant",
                "content": "Theo thong bao da duoc duyet, lich dang ky mon hoc bat dau tu ngay 20/03/2026 va keo dai den 05/04/2026.",
                "created_at": "2026-03-20T07:30:00.000Z",
                "confidence": 0.9,
                "references": [
                    {
                        "id": "ref-003",
                        "title": "Thong bao lich dang ky mon hoc",
                        "href": "/documents/doc-004",
                        "excerpt": "Thong bao da duoc duyet va co the dung cho tra cuu sinh vien.",
                        "status_label": "Approved",
                    }
                ],
                "warnings": [],
            },
        ],
    },
]


def build_initial_state() -> dict:
    return {
        "sessions": deepcopy(SESSION_FIXTURES),
        "documents": deepcopy(DOCUMENT_FIXTURES),
        "submissions": deepcopy(SUBMISSION_FIXTURES),
        "reviews": deepcopy(REVIEW_FIXTURES),
        "jobs": deepcopy(JOB_FIXTURES),
        "admin_users": deepcopy(ADMIN_USER_FIXTURES),
        "role_policies": [
            {
                "role": role,
                "allowed_shells": deepcopy(policy["allowed_shells"]),
                "allowed_routes": deepcopy(policy["allowed_routes"]),
                "requires_internal_email": policy["requires_internal_email"],
            }
            for role, policy in ROLE_ROUTE_MATRIX.items()
        ],
        "system_settings": deepcopy(SYSTEM_SETTING_FIXTURES),
        "audit_logs": deepcopy(AUDIT_LOG_FIXTURES),
        "dense_audit_logs": deepcopy(DENSE_AUDIT_LOG_FIXTURES),
        "conversations": deepcopy(CONVERSATION_FIXTURES),
    }
